module.exports = {
  authRoutes: require("./authRoutes"),
  routeRoutes: require("./routesRoutes"),
  subRouteRoutes: require("./subRoutesRoutes"),
  vehiclesRoutes: require("./vehiclesRoutes"),
  expensesRoutes: require("./expensesRoutes"),
  expenseCategoriesRoutes: require("./expenseCategoriesRoutes"),
  imageUploadRoutes: require("./imageUploadRoutes"),
  productCategoriesRoutes: require("./productCategoriesRoutes"),
  productsRoutes: require("./productsRoutes"),
  staffRoutes: require("./staffRoutes"),
  userRoutes: require("./userRoutes"),
  invoiceRoutes: require("./invoiceRoutes"),
  payoutsRoutes: require("./payoutsRoutes"),
  statsRoutes: require("./statsRoutes"),
};
