module.exports = {
  AuthController: require("./AuthController"),
  RoutesController: require("./RoutesController"),
  SubRoutesController: require("./SubRoutesController"),
  VehiclesController: require("./VehiclesController"),
  ExpensesController: require("./ExpensesController"),
  ExpenseCategoriesController: require("./ExpenseCategoriesController"),
  ImageUploadController: require("./ImageUploadController"),
  ProductCategoriesController: require("./ProductCategoriesController"),
  ProductsController: require("./ProductsController"),
  StaffController: require("./StaffController"),
  UserController: require("./UserController"),
  InvoiceController: require("./InvoiceController"),
  PurchasedItemController: require("./PurchasedItemController"),
  PayoutsController: require("./PayoutsController"),
  StatsController: require("./StatsController"),
};
