module.exports = {
  authCluster: require("./Auth"),
  User: require("./User"),
  Staff: require("./Staff"),
  Routes: require("./Routes"),
  SubRoutes: require("./SubRoutes"),
  Vehicles: require("./Vehicles"),
  Expenses: require("./Expenses"),
  ExpenseCategories: require("./ExpenseCategories"),
  Customers: require("./Customers"),
  ProductCategories: require("./ProductCategories"),
  Products: require("./Products"),
  WalkingCustomers: require("./WalkingCustomers"),
  Invoices: require("./Invoices"),
  PurchasedItems: require("./PurchasedItems"),
  Payouts: require("./Payouts"),
};
